### PR TITLE
sudo install when no write access

### PR DESCRIPTION
**Pull request by albttx**
close: https://github.com/ignite/cli/issues/3041

### CODE REVIEW

**Comment by albttx** [comment]
tested inside a docker container 

```
ubuntu@2f35ee669762:~$ curl 172.17.0.1:3000/cli! | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4291    0  4291    0     0   4260      0 --:--:--  0:00:01 --:--:--  4261
######################################################################## 100.0%
[sudo] password for ubuntu:
Sorry, try again.
[sudo] password for ubuntu:
Installed at /usr/local/bin/ignite
```

**Review by aljo242 — APPROVED** [review]

**Review by jeronimoalbi — APPROVED** [review]
LGTM 👍

**Comment by albttx** [comment]
@fadeev @lubtd  merge ?

**Review by lumtis — APPROVED** [review]
LGTM

**Pull request merged**
